* input: 농어의 길이 (20.4cm)
* output: 농어의 무게 (45.4g)
* model: KNNRegressor(회귀, 지도학습)

In [2]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
import matplotlib.pyplot as plt

perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

## 데이터 준비 - 학습 데이터/ 평가 데이터 분리

In [3]:
import pandas as pd
train_path = 'codes\perch_full.csv'
train_data = pd.read_csv(train_path)

In [12]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(train_data, perch_weight, random_state=42)

In [13]:
train_data

array([19.6, 22. , 18.7, 17.4, 36. , 25. , 40. , 39. , 43. , 22. , 20. ,
       22. , 24. , 27.5, 43. , 40. , 24. , 21. , 27.5, 40. , 32.8, 26.5,
       36.5, 13.7, 22.7, 15. , 37. , 35. , 28.7, 23.5, 39. , 21. , 23. ,
       22. , 44. , 22.5, 19. , 37. , 22. , 25.6, 42. , 34.5])

In [14]:
train_target

array([[  85.],
       [ 135.],
       [  78.],
       [  70.],
       [ 700.],
       [ 180.],
       [ 850.],
       [ 820.],
       [1000.],
       [ 120.],
       [  85.],
       [ 130.],
       [ 225.],
       [ 260.],
       [1100.],
       [ 900.],
       [ 145.],
       [ 115.],
       [ 265.],
       [1015.],
       [ 514.],
       [ 218.],
       [ 685.],
       [  32.],
       [ 145.],
       [  40.],
       [ 690.],
       [ 840.],
       [ 300.],
       [ 170.],
       [ 650.],
       [ 110.],
       [ 150.],
       [ 110.],
       [1000.],
       [ 150.],
       [  80.],
       [ 700.],
       [ 120.],
       [ 197.],
       [1100.],
       [ 556.]])

# 데이터 표준화

In [15]:
length_mean = train_data.mean()
length_std = train_data.std()

train_data = (train_data - length_mean) / length_std
test_data = (test_data - length_mean) / length_std

# KNN 모델 학습

In [16]:
kn = KNeighborsRegressor()

In [22]:
train_data = train_data.reshape(-1, 1)
test_data = test_data.reshape(-1, 1)

In [19]:
kn.fit(train_data, train_target)

KNeighborsRegressor()

# 성능 평가

In [23]:
print('train_score: ', kn.score(train_data, train_target))
print('test_score: ', kn.score(test_data, test_target))

train_score:  0.969912706348246
test_score:  0.992809406101064


# 예측

In [24]:
predict_data = [[40.0]]
kn.predict(predict_data)

array([[1010.]])